### ISSUE TITLE
Breakpoint not working properly

### ISSUE THREAD

**Issue by Min5407** [chakra-ui/panda#1094]
### Description

I have set my breakpoint in the config file but seems like its a mix of em and px.
version: `"@pandacss/dev": "^0.7.0"`

I wanted to change the text color to green when breakpoint is xsmall to sm (120px -150px). The result of min width is correct but for some reason max width become em so it does not work. anyone knows why??

![스크린샷 2023-07-24 오후 5 10 18](https://github.com/chakra-ui/panda/assets/46725533/4b218d01-b4ff-4646-9c22-6a6b8a906d08)

![스크린샷 2023-07-24 오후 5 11 33](https://github.com/chakra-ui/panda/assets/46725533/74bcf9e7-62e4-4e29-a43b-eabb00c8f36a)

![스크린샷 2023-07-24 오후 5 10 56](https://github.com/chakra-ui/panda/assets/46725533/9c8044e3-11e3-4044-aaa2-a0ce615570f2)

### Link to Reproduction

no reproduction

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

next js - app directory and typescript

### Panda CSS Version

0.7.0

### Browser

chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
on a quick glance in the source code, It seems to be because of this line but I don't have the context on this one, perhaps @segunadebayo knows ?
https://github.com/chakra-ui/panda/blob/f4ff7805fcc0a1ab028d6521dd99ba305c7b8c9c/packages/core/src/breakpoints.ts#L108

**Comment by segunadebayo** [comment]
Breakpoints are best defined in `em` unit so they can work regardless of the browser or accessibility zoom level. This is a design decision, not a bug.

Regarding the max-width, this is happening because Panda has a built-in default `xs` breakpoint that has not been overridden. If you change `xSmall` to `xs`, it should work as expected.

The solution is to:
- eject from the built-in preset by passing `eject: true`
- install the `@pandacss/preset-panda`, and tweak the theme.
- add the new theme to the config preset `presets: [customTheme]`
