### ISSUE TITLE
Shorthands not supported inside keyframes

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/panda#1185]
### Description

Inside a keyframe on panda.config.ts, the shorthands don't work: 

theme: {
      extend: {
        keyframes: {
          accordionSlideDown: {
            '0%': {
              height: '0px',
              maxHeight: '0px',
            },
            '100%': {
              height: 'var(--radix-accordion-content-height)',
              //doesn't work
              // maxH: 'var(--radix-accordion-content-height)',
              //does work
              // maxHeight: 'var(--radix-accordion-content-height)'
            },
          },
        }
      }
    },

### Link to Reproduction

https://github.com/FilipePfluck/panda-bugs

### Steps to reproduce

Download the repo, go to panda.config.ts, and uncomment the code.

### JS Framework

React (TS)

### Panda CSS Version

0.10.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @FilipePfluck,

This is by design. We’d like to keep keyframes free of shorthands or utilities for future compatibility with non-web frameworks or motion libraries. The idea is not fully formed yet but that’s why we added this constraint 

Please use the full property name. We’ll update the documentation to reflect this

Thanks for understanding

**Comment by FilipePfluck** [comment]
@segunadebayo I see, thanks for explaining. I don't really mind writing the full name, just opened this issue because I tought it was a bug.
