### ISSUE TITLE
Utility not working for template literal - media queries not generated

### ISSUE THREAD

**Issue by tommyzrce** [chakra-ui/panda#1475]
### Description

When I create a utility and use it with object syntax, it works. When I use it with template literal, it doesn't.

UPDATE FOR OBJECT SYNTAX : even with object syntax, the media queries are **not generated all the time**.
In my utility, if I do ```[`@media (min-width: ${args.token("breakpoints.sm")})`]: {``` or ```xs: {``` the media query is not generated.
However if I do: ```[`@media (min-width: token(breakpoints.xs))`]: {``` the media query is generated.

### Link to Reproduction

Works - objects syntax : https://play.panda-css.com/OBsrwxcN9d
Doesn't work - template literal : https://play.panda-css.com/3Zf9i5da3N

### JS Framework

React

### Panda CSS Version

0.15.4

### Browser

Chrome, Firefox

### Operating System

- [X] Linux

**Comment by segunadebayo** [comment]
Hi @tommyzrce,

This is by design. Utilities and Patterns don't work with template syntax mode.

Please use the object syntax.

**Comment by trompx** [comment]
So can you please specify it more clearly in the docs, especially in the styled-component migration guide and in the utilities/patterns pages. 

It is very misleading, letting you think you can easily migrate while you can't. You have to migrate everything to object syntax if you want to migrate a decent size styled-component project that doesn't just use simple styled.div but utility functions etc.

Can I know why it is like that by design? That would be a plus for panda to support those in both object syntax and template literal.
