### ISSUE TITLE
Style not generated when using external CSS Variables

### ISSUE THREAD

**Issue by navaru** [chakra-ui/panda#1752]
### Description

When adding a semantic token that contains a CSS variable that's external to Panda's config, the style is not generated.

### Link to Reproduction

https://play.panda-css.com/4djgYZmnhI

### Steps to reproduce

In config, a semantic token for shadows, `s1` was added which contains a CSS variable that is not defined in Panda: `var(--shadow-color)`.

It generates the style if a default value is added `var(--shadow-color, blue)`, but it works only for the default value, the CSS variable is not picked up if defined on the element.

### Panda CSS Version

0.20.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The purpose is to be able to use CSS variables that are defined outside of Panda's config.

**Comment by astahmer** [comment]
I *think* it's just because you'd need to define your custom CSS variable on the same DOM element/CSS selector as the ones from Panda CSS tokens, and this is just how CSS works, it's not Panda specific

Looking at the DOM element where you used the `css` fn:
![Screenshot 2023-12-03 at 18 45 10](https://github.com/chakra-ui/panda/assets/47224540/3a01889f-558f-4aed-a5c2-3d4989bbb650)

the `shadows-s1` CSS variable seems greyed out, let's see why !

Looking at the DOM element where all the Panda CSS variables from tokens/semantic tokens are being set: ([`config.cssVarRoot`](https://panda-css.com/docs/references/config#cssvarroot) which defaults to `:where(:root, :host)`)
![Screenshot 2023-12-03 at 18 45 28](https://github.com/chakra-ui/panda/assets/47224540/908b62d4-571e-4e0f-9406-eb17fb91e1b9)

Again, the CSS variable (here, `var(--shadow-color)`) is greyed out, because it's not defined on that selector, if you *somehow* add it, then it works as expected !
![Screenshot 2023-12-03 at 18 49 15](https://github.com/chakra-ui/panda/assets/47224540/8321efb4-4907-4fc6-a969-b6d7d22cb179)
