### ISSUE TITLE
Static CSS files have included @layer order definitions.

### ISSUE THREAD

**Issue by erm1116** [chakra-ui/panda#1938]
### Description

I am building the component library using by Panda CSS.
[From  documentation](https://panda-css.com/docs/guides/component-library#ship-a-static-css-file), I am shipping a static CSS for components library.

But, when I generated a Static CSS file with `panda cssgen` it contains the `@layer` order definition.

In the documentation, in `main.css`, it looks like this
```css
@layer reset, base, tokens, recipes, utilities;.
@import url('@acme-org/design-system/dist/styles.css');
 ...
```
I think that the `@layer` order definition was unintentionally included here, since the order of `@layers` should be defined by the user.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-7ktkbr?file=dist%2Fstyles.css

### Steps to reproduce

1. `npm install`
2. `npm run build:css` (it run `panda cssgen` )
3.  show dist/styles.css
4. See top of the file

### JS Framework

React(TS)

### Panda CSS Version

0.24.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @erm1116,

This is by design. I don't see any downsides to this approach.

The layer order defined by the user and imported before your lib static css will always take precedence over the lib precedence if imported first.

```css
@layers base, reset, utilities, recipes, tokens // user-defined css
@import('component-lib/styles.css') // your lib css (containing the layers params)
```

The first declaration of layer order always wins. Otherwise, it'll be inferred from the css structure.

If you insist, watch out for the hooks PR in #1969, which allows you to customize the css file after generation.
