### ISSUE TITLE
borderWidth doesn't allow any value in strict mode

### ISSUE THREAD

**Issue by iscekic** [chakra-ui/panda#2181]
### Description

The `borderWidth` property doesn't allow any typed value when using strict tokens and strict property values. A workaround exists using the angle brackets escape hatch.

### Link to Reproduction

https://play.panda-css.com/wgCp2V2t4K

### Steps to reproduce

See repro link

### JS Framework

Svelte (TS)

### Panda CSS Version

0.30.2

### Browser

Firefox 122

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
you are using the built-in `@pandacss/preset-base` and the `borderWidth` property is a utility bound to the [`borderWidths`](https://panda-css.com/docs/theming/tokens#border-widths) token category (and values)

since you're using `strictTokens: true`, that means only token values specified bound to that utility (here, any `borderWidths` tokens) are allowed type-wise
if you add any token values in your config, you'll not get any type error anymore
https://play.panda-css.com/uDR5e9OkHh

---

the `strictPropertyValues` config option will not affect the `borderWidth` property as it's not [in the exhaustive list](https://panda-css.com/docs/concepts/writing-styles#strictpropertyvalues)

**Comment by astahmer** [comment]
another alternative would be to :
- either `extend` the utilities with your own `borderWidth` values
- or omit the `values` property inside the `utilities.borderWidth` object from the built-in preset

you can do that like so:

```ts
import { defineConfig } from '@pandacss/dev';

export const config = defineConfig({
  hooks: {
    "config:resolved": ({config, utils}) => {
      return utils.omit(config, ['utilities.borderWidth.values'])
    }
  },
})
  ```

**Comment by iscekic** [comment]
> you are using the built-in `@pandacss/preset-base` and the `borderWidth` property is a utility bound to the [`borderWidths`](https://panda-css.com/docs/theming/tokens#border-widths) token category (and values)
> 
> since you're using `strictTokens: true`, that means only token values specified bound to that utility (here, any `borderWidths` tokens) are allowed type-wise if you add any token values in your config, you'll not get any type error anymore https://play.panda-css.com/uDR5e9OkHh
> 
> the `strictPropertyValues` config option will not affect the `borderWidth` property as it's not [in the exhaustive list](https://panda-css.com/docs/concepts/writing-styles#strictpropertyvalues)

Is there a reason these aren't included and need to be manually re-included in the config?
