### ISSUE TITLE
Hooks `tokens:created` dont work when extending a preset

### ISSUE THREAD

**Issue by ivanbanov** [chakra-ui/panda#2260]
I was playing with a config that uses hooks tokens:created, and not sure why, by when using this config as preset the hooks dont work 🤔 
I created a repo and committed the styled-system folder to make it easier to see it

using the config as it is
https://github.com/ivanbanov/pandacss-codegen-bug/blob/main/styled-system/tokens/tokens.d.ts#L2

using as preset
https://github.com/ivanbanov/pandacss-codegen-bug/blob/main/app/styled-system/tokens/tokens.d.ts#L2

**Comment by astahmer** [comment]
answering here in addition to discord so that it can be indexed in the future:

[this](https://github.com/ivanbanov/pandacss-codegen-bug/blob/6d19f20a30ca24ae08207f331cc1ce2d55e45ce6/app/panda.config.ts#L4) is the issue

-> hooks are [shared in `plugins` not `presets`](https://panda-css.com/docs/concepts/hooks#sharing-hooks)

---

my alternative (multiple exports)

```ts
// (root) panda.config.ts
export const plugin = {
  name: "my-plugin",
  hooks: {
    // ... 
  }
}

export default defineConfig({
  plugins: [plugin],
```

```ts
// (root) panda.config.ts
export const plugin = {
  name: "my-plugin",
  hooks: {
    // ... 
  }
}

export default defineConfig({
  plugins: [plugin],
```
 
 ---
 
 yours (factory function)
 
 ```ts
// panda.config.ts
import { defineConfig } from '@pandacss/dev'
import type { Config } from '@pandacss/dev'

export const config = (options: Config = {}) =>  defineConfig({
  plugins: [],
  ...options,
})

// app/panda.config.ts
import { config } from '../panda.config'

export default config({
  include: ['./src/**/*.{ts,tsx}'],
  outdir: 'styled-system',
})
```
