### ISSUE TITLE
Config Recipe are not extracted properly using `raw` function

### ISSUE THREAD

**Issue by swallowtail62** [chakra-ui/panda#2324]
### Description

When i use [config recipe](https://panda-css.com/docs/concepts/recipes#config-recipe) in component, if call `.raw` function styles are not generated as expected, but if call recipe function directly works properly.

### Link to Reproduction

https://play.panda-css.com/QkL74Op1On

### Steps to reproduce

1. Go to https://play.panda-css.com/QkL74Op1On

### Panda CSS Version

0.34.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
no, it is extracted correctly as you can see here
<img width="884" alt="image" src="https://github.com/chakra-ui/panda/assets/47224540/81353d72-e80f-4320-b64d-5936bda8a8ea">


it's a limitation of config recipes, since they do NOT return atomic CSS, the `raw` function only serves as an identity function and directly returns the arguments that you passed in
in your use-case that means the `css(xxx)` function will receive `{ visual: "solid" }` as an argument, and this is not a valid atomic style object, `css` doesn't know about the variant `visual`

merging styles with config recipes is based on `cx` instead of `css` + `.raw`
https://panda-css.com/docs/concepts/merging-styles#merging-config-recipe-and-style-object

we should probably add a line in the comparison table
https://panda-css.com/docs/concepts/recipes#should-i-use-atomic-or-config-recipes-

if you swap to `cva` you can see that it works as expected
https://play.panda-css.com/QkL74Op1On/uk_7EKsC2p

**Comment by swallowtail62** [comment]
@astahmer 
Thanks for the reply.
I understand that I can simply merge the class names using `cx` function by using css layer.
Thanks for the detailed explanation!
