### ISSUE TITLE
When gradientFrom with light and dark value inside _after, it doesn't work

### ISSUE THREAD

**Issue by tcdw** [chakra-ui/panda#2391]
### Description

I would like making a CSS pseudo-class with gradient for my `<div>` to create a nice-looking visual effect.

The background color of my `<div>` depends on the user's color mode, so I tried to set `gradientFrom` with different `base` and `_dark` value.

Unfortunely, it doesn't work. When user in dark mode, the `gradientFrom` still uses the light mode value.

### Link to Reproduction

https://play.panda-css.com/HHpnRBRNH7

### Steps to reproduce

1. Try to toggle dark/light mode inside the playground editor
4. You can see the main `<div>`'s background color doesn't match with the bottom gradient part

### JS Framework

React (TS)

### Panda CSS Version

0.34.1

### Browser

Chrome/122.0.0.0

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@tcdw works well in your reproduction

https://github.com/chakra-ui/panda/assets/30869823/57e6841f-4643-4c06-9bfc-c45135526e7b

**Comment by tcdw** [comment]
Well, I am not sure if I explained clearly before, but here is what I want:

| Light Mode | Dark Mode |
|-|-|
| ![image](https://github.com/chakra-ui/panda/assets/8687182/db298614-edf2-404a-82cb-9053234220a1) | ![image](https://github.com/chakra-ui/panda/assets/8687182/7d3040b1-6ba9-496d-a8b5-6fe8fed5d3d3) |

In dark mode, I want the value of `gradientFrom` is shown as `yellow.500`, not `blue.500`.

**Comment by anubra266** [comment]
Oh...I see the issue now @tcdw

**Comment by astahmer** [comment]
hey, this is because this ordering of conditions generates invalid CSS (Panda mimics how CSS works, where selectors can't be used inside pseudo elements)
https://panda-css.com/docs/concepts/conditional-styles#before-and-after:~:text=in%20double%20quotes.-,Mixing%20with%20Conditions%3A%20When%20using%20condition%20and%20pseudo%20elements%2C%20prefer%20to,is%20because%20it%20generated%20an%20invalid%20CSS%20structure%20that%20looks%20like%3A,-%26%3A%3Abackdrop%20%7B

if you move the `gradientFrom` outside the `_after` it will work as expected 
https://play.panda-css.com/HHpnRBRNH7/rkMH9bHuur

**Comment by tcdw** [comment]
After moderation like this, it behaves exactly what I would want. Thanks!
