### ISSUE TITLE
Bug with hooks and color opacity modifier

### ISSUE THREAD

**Issue by arenasv86** [chakra-ui/panda#2667]
### Description

When I configure the hook "token:created", to add a prefix to my tokens, the "Color opacity modifier" functionality does not work as expected. It generates a CSS code but it includes the prefix symbol, so it doesn't work.

### Link to Reproduction

https://play.panda-css.com/gJE5S3GyVG

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React

### Panda CSS Version

0.40.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
hey, there's no bug here, but since you are customizing the `token:created` hook, you're also customizing the names of created tokens so you have to mirror those changes in the utilities (instead of relying on the defaults, which expect the dot-delimited syntax)

https://play.panda-css.com/gJE5S3GyVG/jrYOt0YTXb

---

the `@pandacss/preset-base` (currently included by default) is providing [custom utilities](https://panda-css.com/docs/customization/utilities) with a `transform` function for colors that is using the [`createColorMixTransform` ](https://panda-css.com/docs/concepts/color-opacity-modifier), itself using a default provided [`colorMix`](https://github.com/chakra-ui/panda/blob/a5c756077ec8439f3f32e8df3d8d87e435da24e3/packages/core/src/color-mix.ts#L3) fn made for the classic panda way of generating token names (dot delimited syntax), you'll have to use your own

[this test](https://github.com/chakra-ui/panda/blob/bc09d893a63ab2b40f6fe026ab3b7bd62dad289d/packages/token-dictionary/__tests__/color-palette.test.ts#L1093) is using a similar `token:created` hook to emulate the Stitches-like syntax so you can see the resulting tokens
```ts
hooks: {
    "tokens:created": ({ configure }) => {
      configure({
        formatTokenName: (path) => "$" + path.join("-"),
      });
    },
  },
```
