### ISSUE TITLE
Inconsistency in strictTokens mode

### ISSUE THREAD

**Issue by theMosaad** [chakra-ui/panda#815]
### Description

When having `config.StrictTokens: true`, adding an invalid value for `borderTopRadius` doesn't error. However, adding an invalid value for `borderBottomLeftRadius` errors.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-c4cjhy?file=src%2FApp.tsx

### Steps to reproduce

See `App.tsx` in the reproduction link.

### JS Framework

Vite (TS)

### Panda CSS Version

0.4.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by tombstonedguy** [comment]
from version 0.11 on the issue got even worse. since there are generated type definitions like the following:

`ConditionalValue<(string & {}) | RadiusToken> | undefined`

there is no mor illegal use indication.
in the former versions like @theMosaad figured out the generated type looked like:

`ConditionalValue<RadiusToken> | undefined`

at least for the functional properties.
